global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blogapp-api'
    static_configs:
      - targets: ['host.docker.internal:5000']  # BlogApp.Api'nin çalışacağı port
      # - targets: ['userservice:50000']  # BlogApp.Api'nin çalışacağı port
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]
        
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        
  - job_name: 'mongodb'
    static_configs:
      - targets: [ 'mongodb-exporter:9216' ]

  - job_name: 'rabbitmq'
    static_configs:
      - targets: [ 'rabbitmq-exporter:9419' ]